# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'care_main_dialog_base.ui'
#
# Created: Mon Sep 18 09:14:19 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CareDialogBase(object):
    def setupUi(self, CareDialogBase):
        CareDialogBase.setObjectName(_fromUtf8("CareDialogBase"))
        CareDialogBase.resize(880, 538)
        CareDialogBase.setMinimumSize(QtCore.QSize(880, 538))
        self.button_box = QtGui.QDialogButtonBox(CareDialogBase)
        self.button_box.setGeometry(QtCore.QRect(699, 469, 161, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.lineEdit_Password = QtGui.QLineEdit(CareDialogBase)
        self.lineEdit_Password.setGeometry(QtCore.QRect(532, 475, 161, 20))
        self.lineEdit_Password.setObjectName(_fromUtf8("lineEdit_Password"))
        self.Password = QtGui.QLabel(CareDialogBase)
        self.Password.setGeometry(QtCore.QRect(397, 476, 147, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cambria Math"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setStyleSheet(_fromUtf8("font: 75 11pt \"Times New Roman\";\n"
"font: 9pt \"Cambria Math\";"))
        self.Password.setObjectName(_fromUtf8("Password"))
        self.label_14 = QtGui.QLabel(CareDialogBase)
        self.label_14.setGeometry(QtCore.QRect(22, 290, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalSlider_thirdloop = QtGui.QSlider(CareDialogBase)
        self.horizontalSlider_thirdloop.setGeometry(QtCore.QRect(165, 393, 611, 20))
        self.horizontalSlider_thirdloop.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_thirdloop.setObjectName(_fromUtf8("horizontalSlider_thirdloop"))
        self.label = QtGui.QLabel(CareDialogBase)
        self.label.setGeometry(QtCore.QRect(19, 504, 581, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.lcdNumber_2 = QtGui.QLCDNumber(CareDialogBase)
        self.lcdNumber_2.setGeometry(QtCore.QRect(785, 363, 71, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdNumber_2.setPalette(palette)
        self.lcdNumber_2.setStyleSheet(_fromUtf8(""))
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.comboBox__factor_polygon = QtGui.QComboBox(CareDialogBase)
        self.comboBox__factor_polygon.setGeometry(QtCore.QRect(537, 140, 131, 22))
        self.comboBox__factor_polygon.setObjectName(_fromUtf8("comboBox__factor_polygon"))
        self.comboBox_factor_point = QtGui.QComboBox(CareDialogBase)
        self.comboBox_factor_point.setGeometry(QtCore.QRect(537, 240, 131, 22))
        self.comboBox_factor_point.setObjectName(_fromUtf8("comboBox_factor_point"))
        self.label_5 = QtGui.QLabel(CareDialogBase)
        self.label_5.setGeometry(QtCore.QRect(20, 333, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_3 = QtGui.QLabel(CareDialogBase)
        self.label_3.setGeometry(QtCore.QRect(407, 139, 141, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_7 = QtGui.QLabel(CareDialogBase)
        self.label_7.setGeometry(QtCore.QRect(21, 192, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalSlider_firstloop = QtGui.QSlider(CareDialogBase)
        self.horizontalSlider_firstloop.setGeometry(QtCore.QRect(165, 333, 611, 20))
        self.horizontalSlider_firstloop.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_firstloop.setObjectName(_fromUtf8("horizontalSlider_firstloop"))
        self.label_9 = QtGui.QLabel(CareDialogBase)
        self.label_9.setGeometry(QtCore.QRect(407, 188, 141, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(CareDialogBase)
        self.label_10.setGeometry(QtCore.QRect(407, 239, 141, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.comboBox__factor_polyline = QtGui.QComboBox(CareDialogBase)
        self.comboBox__factor_polyline.setGeometry(QtCore.QRect(537, 190, 131, 22))
        self.comboBox__factor_polyline.setObjectName(_fromUtf8("comboBox__factor_polyline"))
        self.comboBox_input_Crime = QtGui.QComboBox(CareDialogBase)
        self.comboBox_input_Crime.setGeometry(QtCore.QRect(133, 288, 725, 22))
        self.comboBox_input_Crime.setObjectName(_fromUtf8("comboBox_input_Crime"))
        self.frame_9 = QtGui.QFrame(CareDialogBase)
        self.frame_9.setGeometry(QtCore.QRect(11, 11, 501, 111))
        self.frame_9.setStyleSheet(_fromUtf8("image: url(:/plugins/Care/Crime_Analyst_lowRes.png);"))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.comboBox_input_polygon = QtGui.QComboBox(CareDialogBase)
        self.comboBox_input_polygon.setGeometry(QtCore.QRect(134, 140, 241, 22))
        self.comboBox_input_polygon.setObjectName(_fromUtf8("comboBox_input_polygon"))
        self.label_4 = QtGui.QLabel(CareDialogBase)
        self.label_4.setGeometry(QtCore.QRect(20, 363, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lcdNumber_3 = QtGui.QLCDNumber(CareDialogBase)
        self.lcdNumber_3.setGeometry(QtCore.QRect(785, 393, 71, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdNumber_3.setPalette(palette)
        self.lcdNumber_3.setStyleSheet(_fromUtf8(""))
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.comboBox_input_point = QtGui.QComboBox(CareDialogBase)
        self.comboBox_input_point.setGeometry(QtCore.QRect(134, 240, 241, 22))
        self.comboBox_input_point.setObjectName(_fromUtf8("comboBox_input_point"))
        self.label_2 = QtGui.QLabel(CareDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 393, 141, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_12 = QtGui.QLabel(CareDialogBase)
        self.label_12.setGeometry(QtCore.QRect(689, 189, 61, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.comboBox__layer_polyline = QtGui.QComboBox(CareDialogBase)
        self.comboBox__layer_polyline.setGeometry(QtCore.QRect(747, 190, 111, 22))
        self.comboBox__layer_polyline.setObjectName(_fromUtf8("comboBox__layer_polyline"))
        self.comboBox__input_polyline = QtGui.QComboBox(CareDialogBase)
        self.comboBox__input_polyline.setGeometry(QtCore.QRect(134, 190, 241, 22))
        self.comboBox__input_polyline.setObjectName(_fromUtf8("comboBox__input_polyline"))
        self.lineEdit_output = QtGui.QLineEdit(CareDialogBase)
        self.lineEdit_output.setGeometry(QtCore.QRect(19, 438, 760, 20))
        self.lineEdit_output.setObjectName(_fromUtf8("lineEdit_output"))
        self.ContactInfo = QtGui.QLabel(CareDialogBase)
        self.ContactInfo.setGeometry(QtCore.QRect(19, 470, 241, 21))
        self.ContactInfo.setStyleSheet(_fromUtf8("font: italic 8pt \"Mongolian Baiti\";"))
        self.ContactInfo.setObjectName(_fromUtf8("ContactInfo"))
        self.lcdNumber_1 = QtGui.QLCDNumber(CareDialogBase)
        self.lcdNumber_1.setGeometry(QtCore.QRect(785, 333, 71, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lcdNumber_1.setPalette(palette)
        self.lcdNumber_1.setStyleSheet(_fromUtf8(""))
        self.lcdNumber_1.setObjectName(_fromUtf8("lcdNumber_1"))
        self.label_8 = QtGui.QLabel(CareDialogBase)
        self.label_8.setGeometry(QtCore.QRect(21, 242, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_2 = QtGui.QFrame(CareDialogBase)
        self.frame_2.setGeometry(QtCore.QRect(512, 11, 361, 111))
        self.frame_2.setStyleSheet(_fromUtf8("image: url(:/plugins/Care/CARE_LOGO.png);"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pushButton_output = QtGui.QPushButton(CareDialogBase)
        self.pushButton_output.setGeometry(QtCore.QRect(785, 437, 75, 23))
        self.pushButton_output.setObjectName(_fromUtf8("pushButton_output"))
        self.label_6 = QtGui.QLabel(CareDialogBase)
        self.label_6.setGeometry(QtCore.QRect(21, 142, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("font: 75 9pt \"Times New Roman\";"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox_layer_polygon = QtGui.QComboBox(CareDialogBase)
        self.comboBox_layer_polygon.setGeometry(QtCore.QRect(747, 140, 111, 22))
        self.comboBox_layer_polygon.setObjectName(_fromUtf8("comboBox_layer_polygon"))
        self.label_13 = QtGui.QLabel(CareDialogBase)
        self.label_13.setGeometry(QtCore.QRect(689, 239, 61, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalSlider_secondloop = QtGui.QSlider(CareDialogBase)
        self.horizontalSlider_secondloop.setGeometry(QtCore.QRect(165, 363, 611, 20))
        self.horizontalSlider_secondloop.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_secondloop.setObjectName(_fromUtf8("horizontalSlider_secondloop"))
        self.comboBox__layer_point = QtGui.QComboBox(CareDialogBase)
        self.comboBox__layer_point.setGeometry(QtCore.QRect(747, 240, 111, 22))
        self.comboBox__layer_point.setObjectName(_fromUtf8("comboBox__layer_point"))
        self.label_11 = QtGui.QLabel(CareDialogBase)
        self.label_11.setGeometry(QtCore.QRect(689, 139, 61, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))

        self.retranslateUi(CareDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), CareDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), CareDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(CareDialogBase)

    def retranslateUi(self, CareDialogBase):
        CareDialogBase.setWindowTitle(_translate("CareDialogBase", "C.A.R.E", None))
        self.Password.setText(_translate("CareDialogBase", "Authentication password", None))
        self.label_14.setText(_translate("CareDialogBase", "Main Crime layer", None))
        self.label.setText(_translate("CareDialogBase", "*** Note: all the combo-boxes above must have values in this version of program, else it will cause an error", None))
        self.lcdNumber_2.setToolTip(_translate("CareDialogBase", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_5.setText(_translate("CareDialogBase", "First loop redundancy", None))
        self.label_3.setText(_translate("CareDialogBase", "Polygon layer\'s factor field", None))
        self.label_7.setText(_translate("CareDialogBase", "Input Polyline Layer", None))
        self.label_9.setText(_translate("CareDialogBase", "Polyline layer\'s factor field", None))
        self.label_10.setText(_translate("CareDialogBase", "Point layer\'s factor field", None))
        self.label_4.setText(_translate("CareDialogBase", "Second loop redundancy", None))
        self.lcdNumber_3.setToolTip(_translate("CareDialogBase", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_2.setText(_translate("CareDialogBase", "Third loop redundancy", None))
        self.label_12.setText(_translate("CareDialogBase", "Layer field", None))
        self.ContactInfo.setText(_translate("CareDialogBase", "contact info: Salehi@consultant.com", None))
        self.lcdNumber_1.setToolTip(_translate("CareDialogBase", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_8.setText(_translate("CareDialogBase", "Input Point Layer", None))
        self.pushButton_output.setText(_translate("CareDialogBase", "Output", None))
        self.label_6.setText(_translate("CareDialogBase", "Input Polygon Layer", None))
        self.label_13.setText(_translate("CareDialogBase", "Layer field", None))
        self.label_11.setText(_translate("CareDialogBase", "Layer field", None))

import resources_rc
